### ISSUE TITLE
Enable students to view the grades

### ISSUE THREAD

**Issue by eyu776** [eyu776/Practice-Scrum-and-GitHub-Flow#1]
### User Story
As a student, I like to be able to view my grades throughout the semester to evaluate and adjust my performance. So, I want to be able to view my grades online because it is convenient to have my grades in one place and without having to calculate it myself on a spreadsheet.

### Task List
- [x] Implement table/schema in database to store grades
- [x] Implement a function that retrieves the grades of a user, and only that user for privacy
- [x] Implement the UI (HTML/CSS) to display the grades to a user
- [x] Implement the views to the backend/database to display the most recent grades to the user

### Acceptance Criteria
* user should only be able to see their own grades and no one else
* user should only be able to see the grades of their current semester courses
